### ISSUE TITLE
Улучшить тестирование презентаций на travis

### ISSUE THREAD

**Issue by AoD314** [UNN-VMK-Software/agile-course-theory#48]
- [ ] В блоках кода должно быть одинаковое выравнивание (4 пробела)
- [ ] Каким-то образом валидировать Markdown (<http://habrahabr.ru/post/235611/>)
- [ ] По идее можно вырезать все куски кода и проверять их на соответствие некоторым общим соглашениям (запускать какие-то тулы)

**Comment by kirill-kornyakov** [comment]
Моved here: https://github.com/kirill-kornyakov/slidy-scripts/blob/master/README.md
